<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Generating_Data_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.empty(), np.zeros(), np.ones(), np.full()

In [ ]:
array_empty = np.empty(shape=(2,3))
array_empty

array([[1.8317069e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
array_0s = np.zeros(shape=(2,5))
array_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
array_0s = np.zeros(shape=(2,5), dtype = np.int8)
array_0s

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
array_1s = np.ones(shape=(2,5))
array_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array_full = np.full(shape=(2,4), fill_value=2023)
array_full

array([[2023, 2023, 2023, 2023],
       [2023, 2023, 2023, 2023]])

"_like" functions

In [ ]:
matrix_A = np.array([[45,56,23,53,78], [45,29,54,86,31], [49,39,52,78,32]])
matrix_A

array([[45, 56, 23, 53, 78],
       [45, 29, 54, 86, 31],
       [49, 39, 52, 78, 32]])

In [ ]:
matrix_A.shape

(3, 5)

In [ ]:
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[            40460352,                    0, -4376688855236805467,
             140688413172144,              9488912],
       [ -305880666143776305,      140688032062384,              9478112,
        -1020080836521940779,      140688032062448],
       [             9478112,  7933418333901674334,      140688031770032,
             140687899050368,                  128]])

In [ ]:
array_0s_like = np.zeros_like(matrix_A)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])