<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Generating_Data_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
array_empty = np.empty(shape=(2,3))
array_empty

array([[1.8317069e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [3]:
array_0s = np.zeros(shape=(2,5))
array_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
array_0s = np.zeros(shape=(2,5), dtype = np.int8)
array_0s

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [5]:
array_1s = np.ones(shape=(2,5))
array_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
array_full = np.full(shape=(2,4), fill_value=2023)
array_full

array([[2023, 2023, 2023, 2023],
       [2023, 2023, 2023, 2023]])

"_like" functions