<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Generating_Data_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.empty(), np.zeros(), np.ones(), np.full()

In [ ]:
array_empty = np.empty(shape=(2,3))
array_empty

array([[1.8317069e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
array_0s = np.zeros(shape=(2,5))
array_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
array_0s = np.zeros(shape=(2,5), dtype = np.int8)
array_0s

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
array_1s = np.ones(shape=(2,5))
array_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array_full = np.full(shape=(2,4), fill_value=2023)
array_full

array([[2023, 2023, 2023, 2023],
       [2023, 2023, 2023, 2023]])

"_like" functions

In [ ]:
matrix_A = np.array([[45,56,23,53,78], [45,29,54,86,31], [49,39,52,78,32]])
matrix_A

array([[45, 56, 23, 53, 78],
       [45, 29, 54, 86, 31],
       [49, 39, 52, 78, 32]])

In [ ]:
matrix_A.shape

(3, 5)

In [ ]:
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[            40460352,                    0, -4376688855236805467,
             140688413172144,              9488912],
       [ -305880666143776305,      140688032062384,              9478112,
        -1020080836521940779,      140688032062448],
       [             9478112,  7933418333901674334,      140688031770032,
             140687899050368,                  128]])

In [ ]:
array_0s_like = np.zeros_like(matrix_A)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

np.arange()

In [17]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [18]:
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
array_rng = np.arange(start = 0, stop = 30, step = 3)
array_rng

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [25]:
array_rng = np.arange(start = 0, stop = 30, step = 3, dtype = np.float64)
array_rng

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [27]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5, dtype = np.int32)
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22], dtype=int32)

## Random Generators

Defining Random Generators

In [31]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [37]:
array_RG = gen(pcg())
array_RG.normal(size= (5,6))

array([[ 1.41211297, -1.13029843,  1.16639585, -0.30130696,  1.28393729,
        -0.74244023],
       [ 0.59302081,  1.57476427,  2.23890392,  0.62105816, -1.75452305,
         1.9963859 ],
       [-0.13898251,  1.28967579, -0.42285762,  1.32236684, -2.41656872,
         1.89877786],
       [-0.39962551,  2.26165046, -1.00187661, -0.06307383,  0.41283159,
        -0.57402208],
       [-0.49789142, -1.59741078,  0.21483799, -0.62504965, -2.98240474,
        -0.411426  ]])

In [47]:
# The result we expect to see every time
array_RG = gen(pcg(seed=365))
array_RG.normal(size= (5,6))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ,
        -0.50922173],
       [-0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ,  0.65526774,
        -0.48095012],
       [-0.5519114 , -0.58578662, -0.98257896,  1.12378166, -1.30984316,
        -0.04703774],
       [ 0.955272  ,  0.26071745, -0.20023668, -1.50172484, -1.4929163 ,
         0.96535084],
       [ 1.18694633, -0.76065577,  1.48158358,  0.01200258, -0.06846959,
         0.25301664]])

In [50]:
# whenever we intend to use a "seed", we'll have to reset it every time
array_RG.normal(size= (5,6))

array([[-0.02153055,  1.27926297,  1.62188437, -0.56612507, -0.51265843,
         0.64317322],
       [ 0.03355112, -0.78542576,  2.4075666 ,  0.28802775, -0.25906657,
        -0.16532638],
       [-0.47735775, -0.52855221,  1.70374643, -0.24469883, -0.14733608,
        -0.4081149 ],
       [ 0.85591897,  0.2208273 , -0.50401804, -0.31628129,  0.37721236,
         0.72377218],
       [-1.05689925, -1.0395866 ,  0.39665421, -0.50851684, -0.38667483,
        -0.28611018]])

Generating Integers, Probabilities and Random Choices

In [51]:
array_RG = gen(pcg(seed = 365))
array_RG.integers(10, size = (5,5))

array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]])

In [52]:
array_RG = gen(pcg(seed = 365))
array_RG.integers(low=10, high = 100, size = (5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [54]:
array_RG = gen(pcg(seed = 365))
array_RG.random(size = (5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [55]:
array_RG = gen(pcg(seed = 365))
array_RG.choice([1,2,3,4,5], size = (5,5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

Generating Arrays From Known Distributions

In [56]:
array_RG = gen(pcg(seed=365))
array_RG.poisson(size=(4,4))

array([[2, 0, 1, 1],
       [2, 1, 1, 0],
       [1, 1, 1, 2],
       [1, 1, 0, 0]])

In [58]:
array_RG = gen(pcg(seed=365))
array_RG.poisson(lam=12, size=(4,4))

array([[13, 14, 14, 17],
       [16,  6, 11, 12],
       [13, 14,  8, 10],
       [13,  9, 12, 16]])

In [60]:
array_RG = gen(pcg(seed=365))
array_RG.binomial(n=100, p=0.4, size=(4,4))

array([[42, 44, 30, 36],
       [45, 36, 41, 38],
       [42, 41, 35, 31],
       [35, 46, 29, 41]])

In [61]:
array_RG = gen(pcg(seed=365))
array_RG.logistic(loc=7, scale= 3.6, size=(4,4))

array([[11.13303466, 11.27355588,  8.90213101,  2.0846028 ],
       [ 9.4686036 , -2.56330625, 10.28062692, -0.59628405],
       [14.16220768,  6.91443754, 12.57534094,  6.37243952],
       [-2.11376299,  9.98682042,  5.03617353,  3.91316566]])

Applications of Random Generators

In [64]:
array_RG = gen(pcg(seed=365))

array_column_1 = array_RG.normal(loc=2, scale=3, size=(1000))
array_column_2 = array_RG.normal(loc=7, scale=2, size=(1000))
array_column_3 = array_RG.logistic(loc=11, scale=3, size=(1000))
array_column_4 = array_RG.exponential(scale=4, size=(1000))
array_column_5 = array_RG.geometric(p=0.7, size=(1000))

In [65]:
random_test_data = np.array([array_column_1, array_column_2, array_column_3, array_column_4, array_column_5])
random_test_data

array([[ 1.59077303,  2.28243293,  1.81098674, ...,  0.1973629 ,
        -2.21015722,  2.91161235],
       [ 6.42174295,  8.57902322,  5.17270135, ...,  4.3465854 ,
         8.2176402 ,  7.90337695],
       [10.14698427, 15.93309953, -0.46878789, ...,  2.66485989,
        12.69328115, 11.79840961],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         2.        ,  1.        ]])

In [66]:
random_test_data.shape

(5, 1000)

In [67]:
np.savetxt("Random-Text-from-NumPy.csv", random_test_data, fmt="%s", delimiter=',')

In [69]:
np.genfromtxt("Random-Text-from-NumPy.csv", delimiter=',')

array([[ 1.59077303,  2.28243293,  1.81098674, ...,  0.1973629 ,
        -2.21015722,  2.91161235],
       [ 6.42174295,  8.57902322,  5.17270135, ...,  4.3465854 ,
         8.2176402 ,  7.90337695],
       [10.14698427, 15.93309953, -0.46878789, ...,  2.66485989,
        12.69328115, 11.79840961],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         2.        ,  1.        ]])