<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Generating_Data_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.empty(), np.zeros(), np.ones(), np.full()

In [ ]:
array_empty = np.empty(shape=(2,3))
array_empty

array([[1.8317069e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
array_0s = np.zeros(shape=(2,5))
array_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
array_0s = np.zeros(shape=(2,5), dtype = np.int8)
array_0s

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
array_1s = np.ones(shape=(2,5))
array_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array_full = np.full(shape=(2,4), fill_value=2023)
array_full

array([[2023, 2023, 2023, 2023],
       [2023, 2023, 2023, 2023]])

"_like" functions

In [ ]:
matrix_A = np.array([[45,56,23,53,78], [45,29,54,86,31], [49,39,52,78,32]])
matrix_A

array([[45, 56, 23, 53, 78],
       [45, 29, 54, 86, 31],
       [49, 39, 52, 78, 32]])

In [ ]:
matrix_A.shape

(3, 5)

In [ ]:
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[            40460352,                    0, -4376688855236805467,
             140688413172144,              9488912],
       [ -305880666143776305,      140688032062384,              9478112,
        -1020080836521940779,      140688032062448],
       [             9478112,  7933418333901674334,      140688031770032,
             140687899050368,                  128]])

In [ ]:
array_0s_like = np.zeros_like(matrix_A)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

np.arange()

In [17]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [18]:
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
array_rng = np.arange(start = 0, stop = 30, step = 3)
array_rng

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [25]:
array_rng = np.arange(start = 0, stop = 30, step = 3, dtype = np.float64)
array_rng

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [27]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5, dtype = np.int32)
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22], dtype=int32)

## Random Generators

Defining Random Generators

In [31]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [37]:
array_RG = gen(pcg())
array_RG.normal(size= (5,6))

array([[ 1.41211297, -1.13029843,  1.16639585, -0.30130696,  1.28393729,
        -0.74244023],
       [ 0.59302081,  1.57476427,  2.23890392,  0.62105816, -1.75452305,
         1.9963859 ],
       [-0.13898251,  1.28967579, -0.42285762,  1.32236684, -2.41656872,
         1.89877786],
       [-0.39962551,  2.26165046, -1.00187661, -0.06307383,  0.41283159,
        -0.57402208],
       [-0.49789142, -1.59741078,  0.21483799, -0.62504965, -2.98240474,
        -0.411426  ]])

In [47]:
# The result we expect to see every time
array_RG = gen(pcg(seed=365))
array_RG.normal(size= (5,6))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ,
        -0.50922173],
       [-0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ,  0.65526774,
        -0.48095012],
       [-0.5519114 , -0.58578662, -0.98257896,  1.12378166, -1.30984316,
        -0.04703774],
       [ 0.955272  ,  0.26071745, -0.20023668, -1.50172484, -1.4929163 ,
         0.96535084],
       [ 1.18694633, -0.76065577,  1.48158358,  0.01200258, -0.06846959,
         0.25301664]])

In [50]:
# whenever we intend to use a "seed", we'll have to reset it every time
array_RG.normal(size= (5,6))

array([[-0.02153055,  1.27926297,  1.62188437, -0.56612507, -0.51265843,
         0.64317322],
       [ 0.03355112, -0.78542576,  2.4075666 ,  0.28802775, -0.25906657,
        -0.16532638],
       [-0.47735775, -0.52855221,  1.70374643, -0.24469883, -0.14733608,
        -0.4081149 ],
       [ 0.85591897,  0.2208273 , -0.50401804, -0.31628129,  0.37721236,
         0.72377218],
       [-1.05689925, -1.0395866 ,  0.39665421, -0.50851684, -0.38667483,
        -0.28611018]])