<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Generating_Data_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.empty(), np.zeros(), np.ones(), np.full()

In [ ]:
array_empty = np.empty(shape=(2,3))
array_empty

array([[1.8317069e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
array_0s = np.zeros(shape=(2,5))
array_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
array_0s = np.zeros(shape=(2,5), dtype = np.int8)
array_0s

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
array_1s = np.ones(shape=(2,5))
array_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array_full = np.full(shape=(2,4), fill_value=2023)
array_full

array([[2023, 2023, 2023, 2023],
       [2023, 2023, 2023, 2023]])

"_like" functions

In [ ]:
matrix_A = np.array([[45,56,23,53,78], [45,29,54,86,31], [49,39,52,78,32]])
matrix_A

array([[45, 56, 23, 53, 78],
       [45, 29, 54, 86, 31],
       [49, 39, 52, 78, 32]])

In [ ]:
matrix_A.shape

(3, 5)

In [ ]:
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[            40460352,                    0, -4376688855236805467,
             140688413172144,              9488912],
       [ -305880666143776305,      140688032062384,              9478112,
        -1020080836521940779,      140688032062448],
       [             9478112,  7933418333901674334,      140688031770032,
             140687899050368,                  128]])

In [ ]:
array_0s_like = np.zeros_like(matrix_A)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

np.arange()

In [17]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [18]:
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
array_rng = np.arange(start = 0, stop = 30, step = 3)
array_rng

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [25]:
array_rng = np.arange(start = 0, stop = 30, step = 3, dtype = np.float64)
array_rng

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [27]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5, dtype = np.int32)
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22], dtype=int32)

## Random Generators

Defining Random Generators

In [31]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [35]:
array_RG = gen(pcg())
array_RG.normal(size=5)

array([ 0.50368038,  0.17513885, -0.07423652, -1.13906455, -0.71039988])