<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/NumPy_DataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Types

In [1]:
import numpy as np

Ndarrays

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
print(array_a)

[1 2 3]


In [5]:
type(array_a)

numpy.ndarray

In [6]:
array_a.shape

(3,)

In [7]:
array_b = np.array([[7,8,9], [10,11,12]])

In [8]:
type(array_b)

numpy.ndarray

In [9]:
array_b.shape[1]

3

In [10]:
array_c = np.array(13)

In [11]:
type(array_c)

numpy.ndarray

In [12]:
print(array_c)

13


In [13]:
array_c.shape

()

In [14]:
array_d = np.array([15]) # one-dimensional array
array_d

array([15])

In [15]:
type(array_d)

numpy.ndarray

In [16]:
array_d.shape

(1,)

In [17]:
array_e = np.array([[12]]) # two-dimensional array
array_e

array([[12]])

Arrays vs. Lists

In [18]:
list_a = [[1,2,3],[4,5,6]]

In [19]:
len(list_a)

2

In [20]:
array_a = np.array(list_a)

In [21]:
type(list_a)

list

In [22]:
type(array_a)

numpy.ndarray

In [23]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [24]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [25]:
array_a.shape

(2, 3)

In [26]:
len(list_a)

2

In [27]:
len(list_a[0])

3

In [28]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [29]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
list_b = list_a[0] + list_a[1]
