<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/NumPy_DataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Types

In [20]:
import numpy as np

Ndarrays

In [ ]:
array_a = np.array([1,2,3])

In [ ]:
array_a

array([1, 2, 3])

In [ ]:
print(array_a)

[1 2 3]


In [ ]:
type(array_a)

numpy.ndarray

In [ ]:
array_a.shape

(3,)

In [ ]:
array_b = np.array([[7,8,9], [10,11,12]])

In [ ]:
type(array_b)

numpy.ndarray

In [ ]:
array_b.shape[1]

3

In [ ]:
array_c = np.array(13)

In [ ]:
type(array_c)

numpy.ndarray

In [ ]:
print(array_c)

13


In [ ]:
array_c.shape

()

In [ ]:
array_d = np.array([15]) # one-dimensional array
array_d

array([15])

In [ ]:
type(array_d)

numpy.ndarray

In [ ]:
array_d.shape

(1,)

In [ ]:
array_e = np.array([[12]]) # two-dimensional array
array_e

array([[12]])

Arrays vs. Lists

In [ ]:
list_a = [[1,2,3],[4,5,6]]

In [ ]:
len(list_a)

2

In [21]:
array_a = np.array(list_a)

In [23]:
type(list_a)

list

In [22]:
type(array_a)

numpy.ndarray

In [24]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [25]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [26]:
array_a.shape

(2, 3)

In [27]:
len(list_a)

2

In [30]:
len(list_a[0])

3