<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Indexing

In [ ]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

Specific Values

In [ ]:
array_a[0]

array([1, 2, 3])

In [ ]:
array_a[1]

array([4, 5, 6])

Note: 

array_a is 2-D

In [ ]:
array_a[0][2]

3

In [ ]:
array_a[0, 2]

3

In [ ]:
array_a[:, 0]

array([1, 4])

Negative Indices

In [ ]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [ ]:
array_a[-1]

array([4, 5, 6])

In [ ]:
array_a[:,-1]

array([3, 6])

## Assigning Values

In [ ]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [ ]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [ ]:
array_a[:,0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [ ]:
list_a = [8,7,8]

array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [ ]:
type(array_a[0])

numpy.ndarray

In [ ]:
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
array_a = 9
array_a

9

In [24]:
type(array_a)

int

In [25]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Elementwise Properties

In [26]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [27]:
array_b = np.array([[1,2,3], [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array_a + 36

array([43, 44, 45])

In [29]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
list_a = [1,2,3]
list_a + [2]

[1, 2, 3, 2]

In [31]:
array_a + 2

array([ 9, 10, 11])

In [32]:
array_a + array_b[0]

array([ 8, 10, 12])