<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/NumPy_DataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Types

In [41]:
import numpy as np

Ndarrays

In [ ]:
array_a = np.array([1,2,3])

In [ ]:
array_a

array([1, 2, 3])

In [ ]:
print(array_a)

[1 2 3]


In [ ]:
type(array_a)

numpy.ndarray

In [ ]:
array_a.shape

(3,)

In [ ]:
array_b = np.array([[7,8,9], [10,11,12]])

In [ ]:
type(array_b)

numpy.ndarray

In [ ]:
array_b.shape[1]

3

In [ ]:
array_c = np.array(13)

In [ ]:
type(array_c)

numpy.ndarray

In [ ]:
print(array_c)

13


In [ ]:
array_c.shape

()

In [ ]:
array_d = np.array([15]) # one-dimensional array
array_d

array([15])

In [ ]:
type(array_d)

numpy.ndarray

In [ ]:
array_d.shape

(1,)

In [ ]:
array_e = np.array([[12]]) # two-dimensional array
array_e

array([[12]])

Arrays vs. Lists

In [ ]:
list_a = [[1,2,3],[4,5,6]]

In [ ]:
len(list_a)

2

In [ ]:
array_a = np.array(list_a)

In [ ]:
type(list_a)

list

In [ ]:
type(array_a)

numpy.ndarray

In [ ]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [ ]:
array_a.shape

(2, 3)

In [ ]:
len(list_a)

2

In [ ]:
len(list_a[0])

3

In [ ]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [ ]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [ ]:
print(list_b)

[1, 2, 3, 4, 5, 6]


In [ ]:
print(array_b)

[5 7 9]


In [ ]:
import math
array_e = math.sqrt(array_a[1,0])
print(array_e)

2.0


In [ ]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

String vs Object vs Numbers

In [45]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter =',',
                              dtype = np.int32)
lending_co_lt

array([[   -1,    -1,    -1, ...,    -1,    -1,    -1],
       [    1,    -1,    -1, ...,    -1,    -1, 16600],
       [    2,    -1,    -1, ...,    -1,    -1, 16600],
       ...,
       [ 1041,    -1,    -1, ...,    -1,    -1, 16600],
       [ 1042,    -1,    -1, ...,    -1,    -1, 15600],
       [ 1043,    -1,    -1, ...,    -1,    -1, 16600]], dtype=int32)