<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/NumPy_DataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Types

In [1]:
import numpy as np

Ndarrays

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
print(array_a)

[1 2 3]


In [5]:
type(array_a)

numpy.ndarray

In [6]:
array_a.shape

(3,)

In [7]:
array_b = np.array([[7,8,9], [10,11,12]])

In [8]:
type(array_b)

numpy.ndarray

In [9]:
array_b.shape[1]

3

In [10]:
array_c = np.array(13)

In [11]:
type(array_c)

numpy.ndarray

In [12]:
print(array_c)

13


In [13]:
array_c.shape

()

In [14]:
array_d = np.array([15]) # one-dimensional array
array_d

array([15])

In [15]:
type(array_d)

numpy.ndarray

In [16]:
array_d.shape

(1,)

In [17]:
array_e = np.array([[12]]) # two-dimensional array
array_e

array([[12]])

Arrays vs. Lists

In [18]:
list_a = [[1,2,3],[4,5,6]]

In [19]:
len(list_a)

2

In [20]:
array_a = np.array(list_a)

In [21]:
type(list_a)

list

In [23]:
type(array_a)

numpy.ndarray

In [22]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [24]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [25]:
array_a.shape

(2, 3)

In [26]:
len(list_a)

2

In [27]:
len(list_a[0])

3

In [28]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [29]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [31]:
print(list_b)

[1, 2, 3, 4, 5, 6]


In [32]:
print(array_b)

[5 7 9]


In [33]:
import math
array_e = math.sqrt(array_a[1,0])
print(array_e)

2.0


In [34]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

String vs Object vs Numbers

In [35]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter =',',
                              dtype = np.int32)
lending_co_lt

array([[   -1,    -1,    -1, ...,    -1,    -1,    -1],
       [    1,    -1,    -1, ...,    -1,    -1, 16600],
       [    2,    -1,    -1, ...,    -1,    -1, 16600],
       ...,
       [ 1041,    -1,    -1, ...,    -1,    -1, 16600],
       [ 1042,    -1,    -1, ...,    -1,    -1, 15600],
       [ 1043,    -1,    -1, ...,    -1,    -1, 16600]], dtype=int32)

In [36]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter =',',
                              dtype = np.object)
lending_co_lt

<ipython-input-36-549b33b80288>:3: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.object)


array([[b'LoanID', b'StringID', b'Product', ..., b'Location', b'Region',
        b'TotalPrice'],
       [b'1', b'id_1', b'Product B', ..., b'Location 2', b'Region 2',
        b'16600.0'],
       [b'2', b'id_2', b'Product B', ..., b'Location 3', b'', b'16600.0'],
       ...,
       [b'1041', b'id_1041', b'Product B', ..., b'Location 23',
        b'Region 4', b'16600.0'],
       [b'1042', b'id_1042', b'Product C', ..., b'Location 52',
        b'Region 6', b'15600.0'],
       [b'1043', b'id_1043', b'Product B', ..., b'Location 142',
        b'Region 6', b'16600.0']], dtype=object)

In [39]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter =',',
                              dtype = (np.int32, np.str, np.str, np.str, np.str, np.str, np.int32))
print(lending_co_lt)

[(  -1, '', '', '', '', '',    -1) (   1, '', '', '', '', '', 16600)
 (   2, '', '', '', '', '', 16600) ... (1041, '', '', '', '', '', 16600)
 (1042, '', '', '', '', '', 15600) (1043, '', '', '', '', '', 16600)]


<ipython-input-39-2228906b7099>:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = (np.int32, np.str, np.str, np.str, np.str, np.str, np.int32))
