<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Indexing

In [2]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

Specific Values

In [3]:
array_a[0]

array([1, 2, 3])

In [4]:
array_a[1]

array([4, 5, 6])

Note: 

array_a is 2-D

In [5]:
array_a[0][2]

3

In [6]:
array_a[0, 2]

3

In [7]:
array_a[:, 0]

array([1, 4])

Negative Indices

In [8]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [9]:
array_a[-1]

array([4, 5, 6])

In [10]:
array_a[:,-1]

array([3, 6])

## Assigning Values

In [11]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [12]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [13]:
array_a[:,0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [14]:
list_a = [8,7,8]

array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [15]:
type(array_a[0])

numpy.ndarray

In [16]:
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [17]:
array_a = 9
array_a

9

In [18]:
type(array_a)

int

In [19]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Elementwise Properties

In [20]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [21]:
array_b = np.array([[1,2,3], [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array_a + 36

array([43, 44, 45])

In [23]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [24]:
list_a = [1,2,3]
list_a + [2]

[1, 2, 3, 2]

In [25]:
array_a + 2

array([ 9, 10, 11])

In [26]:
array_a + array_b[0]

array([ 8, 10, 12])

In [27]:
array_a + array_b[1]

array([11, 13, 15])

In [28]:
array_a * 2

array([14, 16, 18])

## Types of Data Supported by NumPy

In [29]:
array_a = np.array([[1,2,3], [4,5,6]], dtype = "float32")
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [30]:
array_a = np.array([[1,2,3], [4,5,6]], dtype = np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [31]:
array_a = np.array([[1,2,3], [4,5,6]], dtype = np.bool)
array_a

<ipython-input-31-279e5be1e138>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a = np.array([[1,2,3], [4,5,6]], dtype = np.bool)


array([[ True,  True,  True],
       [ True,  True,  True]])