<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Indexing

In [2]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

Specific Values

In [3]:
array_a[0]

array([1, 2, 3])

In [4]:
array_a[1]

array([4, 5, 6])

Note: 

array_a is 2-D

In [5]:
array_a[0][2]

3

In [6]:
array_a[0, 2]

3

In [7]:
array_a[:, 0]

array([1, 4])

Negative Indices

In [8]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [9]:
array_a[-1]

array([4, 5, 6])

In [10]:
array_a[:,-1]

array([3, 6])

## Assigning Values

In [13]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [15]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [18]:
array_a[:,0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [19]:
list_a = [8,7,8]

array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [20]:
type(array_a[0])

numpy.ndarray