<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas Series: .values, .array, .to_numpy()

Converting Series into Arrays

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B': 16600, 'Product C':15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [ ]:
prices_per_category.values

array([22250, 16600, 15600])

In [ ]:
type(prices_per_category.values)

numpy.ndarray

In [ ]:
prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [ ]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [ ]:
prices_per_category.to_numpy()

array([22250, 16600, 15600])

In [ ]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [ ]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [ ]:
type(test_array[0])

numpy.float64

In [ ]:
prices_per_category.values[0]

22250

In [ ]:
type(prices_per_category.values[0])

numpy.int64

In [ ]:
prices_per_category.array[0]

22250

In [ ]:
type(prices_per_category.array[0])

numpy.int64

In [ ]:
prices_per_category.to_numpy()[0]

22250

In [ ]:
type(prices_per_category.to_numpy()[0])

numpy.int64

.sort_values()

In [18]:
numbers = pd.Series([15, 1000, 23, 45, 444])
numbers

0      15
1    1000
2      23
3      45
4     444
dtype: int64

In [20]:
numbers.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [22]:
numbers.sort_values(ascending=True)

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [23]:
numbers.sort_values(ascending=False)

1    1000
4     444
3      45
2      23
0      15
dtype: int64

In [26]:
data = pd.read_csv('Location.csv', squeeze = True)
location_data = data.copy()
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [28]:
location_data.sort_values()

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [29]:
location_data.sort_values(ascending=True)

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [30]:
location_data.sort_values(ascending=False)

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

Notes:

.sort_values() arranges the values of the object it's been applied to

The index values comply with the object's data that will lead the way

Attribute and Method Chaining 

Method chaining 

* organizes and applies several method calls on certain object in a given order

* each call performs its action and returns an intermediate output

* every next method from the chain respects the value returned by the previous one

In [31]:
location_data.index

RangeIndex(start=0, stop=1043, step=1)

In [32]:
location_data.name

'Location'

In [33]:
location_data.index.name

In [37]:
location_data.index.name = 'Index'

In [38]:
location_data

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [39]:
location_data.index.name 

'Index'

In [40]:
location_data.sort_values()

Index
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [41]:
location_data.sort_values().head()

Index
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
Name: Location, dtype: object

In [42]:
location_data.sort_values().tail()

Index
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, dtype: object

In [43]:
location_data.index

RangeIndex(start=0, stop=1043, step=1, name='Index')

In [44]:
type(location_data.index)

pandas.core.indexes.range.RangeIndex

In [45]:
location_data.index.to_numpy()

array([   0,    1,    2, ..., 1040, 1041, 1042])

.sort_index()

.sort_index() 

creates a temporary copy of the object's data it^s been applied to and displays the output of its manipulation



In [46]:
location_data.head()

Index
0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [47]:
location_data_sv = location_data.sort_values(ascending=False)
location_data_sv.head()

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [48]:
location_data_sv.index

Int64Index([ 372,  757,  128,  482,  271,  669,  612,   29,  518,  598,
            ...
             904,  912, 1010,   14,  716,  202,  298,  637,  884,  465],
           dtype='int64', name='Index', length=1043)

In [49]:
location_data_sv.index.sort_values()

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
           dtype='int64', name='Index', length=1043)

In [51]:
location_data_sv.index = location_data_sv.index.sort_values()

In [52]:
location_data_sv

Index
0       Location 99
1       Location 98
2       Location 97
3       Location 97
4       Location 97
           ...     
1038    Location 10
1039    Location 10
1040     Location 1
1041     Location 1
1042     Location 1
Name: Location, Length: 1043, dtype: object

In [54]:
location_data_sv = location_data.sort_values(ascending=False)
location_data_sv.head()

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [55]:
location_data_sv.sort_index()

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [56]:
location_data_sv

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [57]:
location_data_sv = location_data.sort_index(ascending=True)
location_data_sv.head()

Index
0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object