<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas Series: .values, .array, .to_numpy()

Converting Series into Arrays

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B': 16600, 'Product C':15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [ ]:
prices_per_category.values

array([22250, 16600, 15600])

In [ ]:
type(prices_per_category.values)

numpy.ndarray

In [ ]:
prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [ ]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [ ]:
prices_per_category.to_numpy()

array([22250, 16600, 15600])

In [ ]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [ ]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [ ]:
type(test_array[0])

numpy.float64

In [ ]:
prices_per_category.values[0]

22250

In [ ]:
type(prices_per_category.values[0])

numpy.int64

In [ ]:
prices_per_category.array[0]

22250

In [ ]:
type(prices_per_category.array[0])

numpy.int64

In [ ]:
prices_per_category.to_numpy()[0]

22250

In [ ]:
type(prices_per_category.to_numpy()[0])

numpy.int64

.sort_values()

In [18]:
numbers = pd.Series([15, 1000, 23, 45, 444])
numbers

0      15
1    1000
2      23
3      45
4     444
dtype: int64

In [20]:
numbers.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64