<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas Series: .values, .array, .to_numpy()

In [1]:
import pandas as pd
import numpy as np

In [2]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B': 16600, 'Product C':15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [3]:
prices_per_category.values

array([22250, 16600, 15600])

In [4]:
type(prices_per_category.values)

numpy.ndarray

In [5]:
prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [6]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [7]:
prices_per_category.to_numpy()

array([22250, 16600, 15600])

In [8]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [10]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [11]:
type(test_array[0])

numpy.float64

In [13]:
prices_per_category.values[0]

22250

In [14]:
type(prices_per_category.values[0])

numpy.int64

In [15]:
prices_per_category.array[0]

22250

In [16]:
type(prices_per_category.array[0])

numpy.int64

In [17]:
prices_per_category.to_numpy()[0]

22250

In [18]:
type(prices_per_category.to_numpy()[0])

numpy.int64