<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Preprocessing_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Checking for Missing Values 

In [ ]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter=',')

In [ ]:
np.isnan(lending_co_data_numeric).sum()

0

In [ ]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ';')

In [ ]:
np.isnan(lending_co_data_numeric_NAN)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [ ]:
np.isnan(lending_co_data_numeric_NAN).sum()

260

In [ ]:
# lending_co_data_numeric_NAN = np.genfromtxt("Lending-company-Numeric-NAN.csv", 
#                                            delimiter = ';',
#                                            filling_values = 0)

In [ ]:
np.isnan(lending_co_data_numeric_NAN).sum()

260

In [ ]:
temporary_fill = np.nanmax(lending_co_data_numeric_NAN).round(2) + 1

In [ ]:
temporary_fill

64002.0

In [ ]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-company-Numeric-NAN.csv", 
                                            delimiter = ';',
                                            filling_values = temporary_fill)

In [ ]:
np.isnan(lending_co_data_numeric_NAN)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [ ]:
np.isnan(lending_co_data_numeric_NAN).sum()

0

Substituting Missing Values

In [ ]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
temporary_mean = np.nanmean(lending_co_data_numeric_NAN, axis = 0).round(2)

In [ ]:
temporary_mean[0]

2250.25

In [ ]:
temporary_fill = np.nanmax(lending_co_data_numeric_NAN).round(2) + 1

lending_co_data_numeric_NAN = np.genfromtxt('Lending-company-Numeric-NAN.csv',
                                            delimiter = ';',
                                            filling_values = temporary_fill)
lending_co_data_numeric_NAN

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]])

In [ ]:
temporary_fill

64002.0

In [ ]:
np.mean(lending_co_data_numeric_NAN[:,0]).round(2)

4263.25

In [ ]:
temporary_mean[0]

2250.25

In [ ]:
lending_co_data_numeric_NAN[:,0] = np.where(lending_co_data_numeric_NAN[:,0] == temporary_fill,
                                            temporary_mean[0],
                                            lending_co_data_numeric_NAN[:,0])

In [ ]:
np.mean(lending_co_data_numeric_NAN[:,0]).round(2)

2250.25

In [ ]:
for i in range(lending_co_data_numeric_NAN.shape[1]):
  lending_co_data_numeric_NAN[:,1] = np.where(lending_co_data_numeric_NAN[:,1] < 0,
                                              0,
                                              lending_co_data_numeric_NAN[:,1])

Reshaping

In [ ]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter = ',')

In [ ]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
lending_co_data_numeric.shape

(1043, 6)

In [ ]:
np.reshape(lending_co_data_numeric, (6,1043))

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

In [ ]:
np.transpose(lending_co_data_numeric)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]])

In [ ]:
np.reshape(lending_co_data_numeric, (2,3,1043))

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

       [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]])

Removing Values

In [ ]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.delete(lending_co_data_numeric, 0).shape

(6257,)

In [ ]:
lending_co_data_numeric.size

6258

In [ ]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.delete(lending_co_data_numeric, 0, axis = 1)

array([[   40.,   365.,  3121.,  4241., 13621.],
       [   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.delete(lending_co_data_numeric, 1, axis = 1)

array([[ 2000.,   365.,  3121.,  4241., 13621.],
       [ 2000.,   365.,  3061.,  4171., 15041.],
       [ 1000.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  4201.,  5001., 16600.],
       [ 1000.,   365.,  2080.,  3320., 15600.],
       [ 2000.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.delete(lending_co_data_numeric, [0,2,4], axis = 1)

array([[   40.,  3121., 13621.],
       [   40.,  3061., 15041.],
       [   40.,  2160., 15340.],
       ...,
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.],
       [   40.,  4601., 16600.]])

In [ ]:
np.delete(np.delete(lending_co_data_numeric, [0,2,4], axis = 1), [0,2,-1], axis = 0)

array([[   40.,  3061., 15041.],
       [   40.,  3041., 15321.],
       [   50.,  3470., 13720.],
       ...,
       [   40.,  4240., 16600.],
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.]])

Sorting Data

In [ ]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [ ]:
np.sort(lending_co_data_numeric).shape

(1043, 6)

In [ ]:
np.sort(lending_co_data_numeric, axis = 0)

array([[ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.8700e+03, -2.8700e+03,
        -3.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.5500e+03, -2.1000e+03,
         1.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.4500e+03, -2.0000e+03,
         1.1000e+03],
       ...,
       [ 9.0000e+03,  1.2500e+02,  3.6500e+02,  1.6751e+04,  1.8751e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.7650e+04,  2.0001e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.9001e+04,  2.2001e+04,
         6.4001e+04]])

In [ ]:
np.set_printoptions(suppress = True)

In [ ]:
np.sort(lending_co_data_numeric, axis = None)

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.])

In [ ]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [ ]:
np.sort(-lending_co_data_numeric)

array([[-13621.,  -4241.,  -3121.,  -2000.,   -365.,    -40.],
       [-15041.,  -4171.,  -3061.,  -2000.,   -365.,    -40.],
       [-15340.,  -3280.,  -2160.,  -1000.,   -365.,    -40.],
       ...,
       [-16600.,  -5001.,  -4201.,  -2000.,   -365.,    -40.],
       [-15600.,  -3320.,  -2080.,  -1000.,   -365.,    -40.],
       [-16600.,  -4601.,  -4601.,  -2000.,   -365.,    -40.]])

In [ ]:
-np.sort(-lending_co_data_numeric)

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]])

In [ ]:
-np.sort(lending_co_data_numeric)

array([[   -40.,   -365.,  -2000.,  -3121.,  -4241., -13621.],
       [   -40.,   -365.,  -2000.,  -3061.,  -4171., -15041.],
       [   -40.,   -365.,  -1000.,  -2160.,  -3280., -15340.],
       ...,
       [   -40.,   -365.,  -2000.,  -4201.,  -5001., -16600.],
       [   -40.,   -365.,  -1000.,  -2080.,  -3320., -15600.],
       [   -40.,   -365.,  -2000.,  -4601.,  -4601., -16600.]])

In [ ]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.sort(lending_co_data_numeric[:,3])

array([-2870., -2550., -2450., ..., 16751., 17650., 19001.])

In [ ]:
lending_co_data_numeric[:,3].sort()
lending_co_data_numeric

array([[ 2000.,    40.,   365., -2870.,  4241., 13621.],
       [ 2000.,    40.,   365., -2550.,  4171., 15041.],
       [ 1000.,    40.,   365., -2450.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., 16751.,  5001., 16600.],
       [ 1000.,    40.,   365., 17650.,  3320., 15600.],
       [ 2000.,    40.,   365., 19001.,  4601., 16600.]])

Argument Functions

np.argsort()

In [ ]:
lending_co_data_numeric

array([[ 2000.,    40.,   365., -2870.,  4241., 13621.],
       [ 2000.,    40.,   365., -2550.,  4171., 15041.],
       [ 1000.,    40.,   365., -2450.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., 16751.,  5001., 16600.],
       [ 1000.,    40.,   365., 17650.,  3320., 15600.],
       [ 2000.,    40.,   365., 19001.,  4601., 16600.]])

In [ ]:
np.argsort(lending_co_data_numeric)

array([[3, 1, 2, 0, 4, 5],
       [3, 1, 2, 0, 4, 5],
       [3, 1, 2, 0, 4, 5],
       ...,
       [1, 2, 0, 4, 5, 3],
       [1, 2, 0, 4, 5, 3],
       [1, 2, 0, 4, 5, 3]])

In [ ]:
np.argsort(lending_co_data_numeric, axis = 0)

array([[ 537,  443,    0,    0,   32,  482],
       [ 639,  327,  687,    1,  166,  493],
       [ 849,  432,  688,    2,   85,  166],
       ...,
       [  27,  326,  355, 1040, 1019,  568],
       [ 277,   27,  357, 1041, 1033,  534],
       [ 420,  408, 1042, 1042,  912,   27]])

In [ ]:
lending_co_data_numeric[482,5]

-350.0

In [ ]:
lending_co_data_numeric = lending_co_data_numeric[np.argsort(lending_co_data_numeric[:,0])]
lending_co_data_numeric

array([[ 1000.,    40.,   365.,  3418.,  3400., 15600.],
       [ 1000.,    40.,   365.,  3750.,  3800., 15600.],
       [ 1000.,    40.,   365.,  5500.,  3950., 15600.],
       ...,
       [ 9000.,   165.,   365.,  -750., 16846., 64001.],
       [ 9000.,   125.,   365.,  2981., 15751., 38626.],
       [ 9000.,   125.,   365.,  3321., 14251., 25626.]])

In [ ]:
lending_co_data_numeric.argsort(axis = 0)

array([[   0,   22,    0,  342,  199,  172],
       [ 155,   62,  687,  650,   53,  160],
       [ 156,   38,  688,  177,  169,   53],
       ...,
       [1022, 1042,  355,  412, 1037, 1023],
       [1031, 1039,  357,  194, 1029, 1024],
       [1042, 1040, 1042,  716, 1027, 1040]])

In [ ]:
lending_co_data_numeric

array([[ 1000.,    40.,   365.,  3418.,  3400., 15600.],
       [ 1000.,    40.,   365.,  3750.,  3800., 15600.],
       [ 1000.,    40.,   365.,  5500.,  3950., 15600.],
       ...,
       [ 9000.,   165.,   365.,  -750., 16846., 64001.],
       [ 9000.,   125.,   365.,  2981., 15751., 38626.],
       [ 9000.,   125.,   365.,  3321., 14251., 25626.]])

np.argwhere()

In [ ]:
np.argwhere(lending_co_data_numeric)

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]])

In [ ]:
np.argwhere(lending_co_data_numeric == False)

array([[219,   4],
       [649,   3]])

In [ ]:
lending_co_data_numeric[430]

array([ 2000.,    50.,   365.,  7951.,  5251., 20250.])

In [ ]:
lending_co_data_numeric

array([[ 1000.,    40.,   365.,  3418.,  3400., 15600.],
       [ 1000.,    40.,   365.,  3750.,  3800., 15600.],
       [ 1000.,    40.,   365.,  5500.,  3950., 15600.],
       ...,
       [ 9000.,   165.,   365.,  -750., 16846., 64001.],
       [ 9000.,   125.,   365.,  2981., 15751., 38626.],
       [ 9000.,   125.,   365.,  3321., 14251., 25626.]])

In [ ]:
np.argwhere(lending_co_data_numeric %2 == 0)

array([[   0,    0],
       [   0,    1],
       [   0,    3],
       ...,
       [1041,    5],
       [1042,    0],
       [1042,    5]])

In [ ]:
np.isnan(lending_co_data_numeric).sum()

0

In [ ]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.argwhere(np.isnan(lending_co_data_numeric_NAN))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [ ]:
lending_co_data_numeric_NAN[928]

array([ 2000.,    nan,    nan,    nan,  6601., 16600.])

In [ ]:
for array_index in np.argwhere(np.isnan(lending_co_data_numeric_NAN)):
  lending_co_data_numeric_NAN[array_index[0], array_index[1]] = 0

In [ ]:
lending_co_data_numeric_NAN[928]

array([ 2000.,     0.,     0.,     0.,  6601., 16600.])

In [ ]:
np.isnan(lending_co_data_numeric_NAN).sum()

0

Shuffling Data

In [ ]:
lending_co_data_numeric = np.loadtxt('Lending-company-Numeric.csv', delimiter = ',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [ ]:
np.random.shuffle(lending_co_data_numeric)

In [ ]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.]])

In [ ]:
lending_co_data_numeric = np.loadtxt('Lending-company-Numeric.csv', delimiter = ',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
from numpy.random import shuffle

In [ ]:
shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 1000.,    40.,   365.,  2200.,  3400., 15600.],
       [ 2000.,    40.,   365.,  3401.,  4601., 16600.],
       [ 4000.,    50.,   365.,  5900.,  7500., 22250.],
       ...,
       [ 2000.,    40.,   365.,  3160.,  4440., 15600.],
       [ 4000.,    50.,   365.,  6500.,  7700., 19310.],
       [ 2000.,    50.,   365.,  2801.,  3626.,  4676.]])

In [ ]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [ ]:
array_RG = gen(pcg())
array_RG.shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 1000.,    40.,   365.,  2560.,  3680., 14340.],
       [ 2000.,    50.,   365.,  3551.,  4751., 19101.],
       [ 1000.,    50.,   365.,   800.,  1450., 19250.],
       ...,
       [ 2000.,    50.,   365.,  3650.,  4950., 19150.],
       [ 2000.,    40.,   365.,  2981.,  3451.,  7781.],
       [ 4000.,    50.,   365.,  5750.,  7350., 22250.]])

In [ ]:
array_RG = gen(pcg(seed=365))
array_RG.shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  2941.,  3621., 15241.],
       [ 1000.,    50.,   365.,   450.,  2050., 12000.],
       [ 2000.,    40.,   365.,  3681.,  6081., 16241.],
       ...,
       [ 9000.,   125.,   365., 19001., 22001., 54625.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16071.],
       [ 1000.,    50.,   365.,   250.,   850.,  5050.]])

Casting

In [ ]:
lending_co_data_numeric.astype(dtype = np.int32)

array([[ 2000,    40,   365,  2941,  3621, 15241],
       [ 1000,    50,   365,   450,  2050, 12000],
       [ 2000,    40,   365,  3681,  6081, 16241],
       ...,
       [ 9000,   125,   365, 19001, 22001, 54625],
       [ 2000,    40,   365,  4601,  4601, 16071],
       [ 1000,    50,   365,   250,   850,  5050]], dtype=int32)

In [ ]:
lending_co_data_numeric.astype(dtype = np.str)

<ipython-input-80-25dbd518c046>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric.astype(dtype = np.str)


array([['2000.0', '40.0', '365.0', '2941.0', '3621.0', '15241.0'],
       ['1000.0', '50.0', '365.0', '450.0', '2050.0', '12000.0'],
       ['2000.0', '40.0', '365.0', '3681.0', '6081.0', '16241.0'],
       ...,
       ['9000.0', '125.0', '365.0', '19001.0', '22001.0', '54625.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16071.0'],
       ['1000.0', '50.0', '365.0', '250.0', '850.0', '5050.0']],
      dtype='<U32')

In [ ]:
lending_co_data_numeric = lending_co_data_numeric.astype(dtype = np.str)

<ipython-input-81-a6af592c9966>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric = lending_co_data_numeric.astype(dtype = np.str)


In [ ]:
lending_co_data_numeric

array([['2000.0', '40.0', '365.0', '2941.0', '3621.0', '15241.0'],
       ['1000.0', '50.0', '365.0', '450.0', '2050.0', '12000.0'],
       ['2000.0', '40.0', '365.0', '3681.0', '6081.0', '16241.0'],
       ...,
       ['9000.0', '125.0', '365.0', '19001.0', '22001.0', '54625.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16071.0'],
       ['1000.0', '50.0', '365.0', '250.0', '850.0', '5050.0']],
      dtype='<U32')

In [ ]:
type(lending_co_data_numeric)

numpy.ndarray

In [ ]:
# ERROR - We can't directly cast these strings into integers
lending_co_data_numeric.astype(dtype = np.int32)

ValueError: ignored

In [ ]:
lending_co_data_numeric = lending_co_data_numeric.astype(dtype = np.float32)
lending_co_data_numeric.astype(dtype = np.int32)

array([[ 2000,    40,   365,  2941,  3621, 15241],
       [ 1000,    50,   365,   450,  2050, 12000],
       [ 2000,    40,   365,  3681,  6081, 16241],
       ...,
       [ 9000,   125,   365, 19001, 22001, 54625],
       [ 2000,    40,   365,  4601,  4601, 16071],
       [ 1000,    50,   365,   250,   850,  5050]], dtype=int32)

In [ ]:
lending_co_data_numeric = np.loadtxt('Lending-company-Numeric.csv', delimiter = ',')
lending_co_data_numeric = lending_co_data_numeric.astype(dtype = np.str)
lending_co_data_numeric

<ipython-input-86-2010d6477196>:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_data_numeric = lending_co_data_numeric.astype(dtype = np.str)


array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [ ]:
lending_co_data_numeric.astype(dtype = np.float32).astype(dtype = np.int32)
lending_co_data_numeric

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

Data Striping

In [91]:
lending_co_total_price = np.genfromtxt('Lending-Company-Total-Price.csv', 
                                       delimiter = ',', 
                                       dtype = np.str,
                                       skip_header = 1,
                                       usecols = [1,2,4])
lending_co_total_price

<ipython-input-91-94e890153d76>:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str,


array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']], dtype='<U12')

In [92]:
np.chararray.strip(lending_co_total_price[:,0], 'id_')

chararray(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
           '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
           '23', '24', '25', '26', '27', '28', '29', '30', '31', '32',
           '33', '34', '35', '36', '37', '38', '39', '40', '41', '42',
           '43', '44', '45', '46', '47', '48', '49', '50', '51', '52',
           '53', '54', '55', '56', '57', '58', '59', '60', '61', '62',
           '63', '64', '65', '66', '67', '68', '69', '70', '71', '72',
           '73', '74', '75', '76', '77', '78', '79', '80', '81', '82',
           '83', '84', '85', '86', '87', '88', '89', '90', '91', '92',
           '93', '94', '95', '96', '97', '98', '99', '100', '101', '102',
           '103', '104', '105', '106', '107', '108', '109', '110', '111',
           '112', '113', '114', '115', '116', '117', '118', '119', '120',
           '121', '122', '123', '124', '125', '126', '127', '128', '129',
           '130', '131', '132', '133', '134', '135', '136', '1

In [93]:
lending_co_total_price[:,0] = np.chararray.strip(lending_co_total_price[:,0], 'id_')
lending_co_total_price[:,1] = np.chararray.strip(lending_co_total_price[:,1], 'Product ')
lending_co_total_price[:,2] = np.chararray.strip(lending_co_total_price[:,0], 'Location ')
lending_co_total_price

array([['1', 'B', '1'],
       ['2', 'B', '2'],
       ['3', 'C', '3'],
       ...,
       ['413', 'B', '413'],
       ['414', 'C', '414'],
       ['415', 'A', '415']], dtype='<U12')

In [95]:
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'A', 1, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'B', 2, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'C', 3, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'D', 4, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'E', 5, lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'F', 6, lending_co_total_price[:,1])

lending_co_total_price

array([['1', '2', '1'],
       ['2', '2', '2'],
       ['3', '3', '3'],
       ...,
       ['413', '2', '413'],
       ['414', '3', '414'],
       ['415', '1', '415']], dtype='<U12')

In [97]:
lending_co_total_price = lending_co_total_price.astype(dtype = np.int32)
lending_co_total_price

array([[  1,   2,   1],
       [  2,   2,   2],
       [  3,   3,   3],
       ...,
       [413,   2, 413],
       [414,   3, 414],
       [415,   1, 415]], dtype=int32)

Stacking

In [98]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [    0.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [104]:
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,0]))

array([['2000.0', '2000.0', '1000.0', ..., '2000.0', '1000.0', '2000.0'],
       ['2000.0', '2000.0', '1000.0', ..., '2000.0', '1000.0', '2000.0']],
      dtype='<U32')

In [105]:
np.transpose(lending_co_data_numeric[:,:2])

array([['2000.0', '2000.0', '1000.0', ..., '2000.0', '1000.0', '2000.0'],
       ['40.0', '40.0', '40.0', ..., '40.0', '40.0', '40.0']],
      dtype='<U32')

In [107]:
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,1]), axis = 1)

array([['2000.0', '40.0'],
       ['2000.0', '40.0'],
       ['1000.0', '40.0'],
       ...,
       ['2000.0', '40.0'],
       ['1000.0', '40.0'],
       ['2000.0', '40.0']], dtype='<U32')

In [111]:
# ERROR - the arrays must be the same shape
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,1], lending_co_data_numeric[:, :2]), axis = 1)

ValueError: ignored

In [112]:
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,1], lending_co_data_numeric[:,2]), axis = 1)

array([['2000.0', '40.0', '365.0'],
       ['2000.0', '40.0', '365.0'],
       ['1000.0', '40.0', '365.0'],
       ...,
       ['2000.0', '40.0', '365.0'],
       ['1000.0', '40.0', '365.0'],
       ['2000.0', '40.0', '365.0']], dtype='<U32')

In [113]:
lending_co_data_numeric_NAN.shape

(1043, 6)

In [116]:
np.vstack((lending_co_data_numeric, lending_co_data_numeric_NAN))

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['0.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [117]:
np.vstack((lending_co_data_numeric, lending_co_data_numeric_NAN)).shape

(2086, 6)

In [118]:
np.hstack((lending_co_data_numeric, lending_co_data_numeric_NAN))

array([['2000.0', '40.0', '365.0', ..., '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', ..., '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', ..., '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', ..., '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', ..., '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', ..., '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [119]:
np.hstack((lending_co_data_numeric, lending_co_data_numeric_NAN)).shape

(1043, 12)

In [120]:
lending_co_data_numeric_NAN.shape

(1043, 6)

In [122]:
np.dstack((lending_co_data_numeric, lending_co_data_numeric_NAN))

array([[['2000.0', '2000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['3121.0', '3121.0'],
        ['4241.0', '4241.0'],
        ['13621.0', '13621.0']],

       [['2000.0', '2000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['3061.0', '3061.0'],
        ['4171.0', '4171.0'],
        ['15041.0', '15041.0']],

       [['1000.0', '1000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['2160.0', '2160.0'],
        ['3280.0', '3280.0'],
        ['15340.0', '15340.0']],

       ...,

       [['2000.0', '0.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['4201.0', '4201.0'],
        ['5001.0', '5001.0'],
        ['16600.0', '16600.0']],

       [['1000.0', '1000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['2080.0', '2080.0'],
        ['3320.0', '3320.0'],
        ['15600.0', '15600.0']],

       [['2000.0', '2000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['4601.0

In [123]:
np.dstack((lending_co_data_numeric, lending_co_data_numeric_NAN))[0]

array([['2000.0', '2000.0'],
       ['40.0', '40.0'],
       ['365.0', '365.0'],
       ['3121.0', '3121.0'],
       ['4241.0', '4241.0'],
       ['13621.0', '13621.0']], dtype='<U32')

In [124]:
np.dstack((lending_co_data_numeric, lending_co_data_numeric_NAN))[0,:,0]

array(['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
      dtype='<U32')

In [125]:
np.stack((lending_co_data_numeric, lending_co_data_numeric_NAN), axis = -1)

array([[['2000.0', '2000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['3121.0', '3121.0'],
        ['4241.0', '4241.0'],
        ['13621.0', '13621.0']],

       [['2000.0', '2000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['3061.0', '3061.0'],
        ['4171.0', '4171.0'],
        ['15041.0', '15041.0']],

       [['1000.0', '1000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['2160.0', '2160.0'],
        ['3280.0', '3280.0'],
        ['15340.0', '15340.0']],

       ...,

       [['2000.0', '0.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['4201.0', '4201.0'],
        ['5001.0', '5001.0'],
        ['16600.0', '16600.0']],

       [['1000.0', '1000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['2080.0', '2080.0'],
        ['3320.0', '3320.0'],
        ['15600.0', '15600.0']],

       [['2000.0', '2000.0'],
        ['40.0', '40.0'],
        ['365.0', '365.0'],
        ['4601.0

Concatenate

In [126]:
lending_co_data_numeric

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [127]:
np.concatenate((lending_co_data_numeric[0,:], lending_co_data_numeric[1,:]))

array(['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0', '2000.0',
       '40.0', '365.0', '3061.0', '4171.0', '15041.0'], dtype='<U32')

In [128]:
np.concatenate((lending_co_data_numeric, lending_co_data_numeric)).shape

(2086, 6)

In [129]:
np.concatenate((lending_co_data_numeric, lending_co_data_numeric), axis = 1)

array([['2000.0', '40.0', '365.0', ..., '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', ..., '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', ..., '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', ..., '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', ..., '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', ..., '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [130]:
np.concatenate((lending_co_data_numeric, lending_co_data_numeric_NAN), axis = 1).shape

(1043, 12)

Unique