<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Statistics_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.mean()

In [ ]:
matrix_A = np.array([[2,3,4,8,5], [5,3,3,4,6], [5,9,3,2,4], [2,3,1,2,2]])
matrix_A

array([[2, 3, 4, 8, 5],
       [5, 3, 3, 4, 6],
       [5, 9, 3, 2, 4],
       [2, 3, 1, 2, 2]])

In [ ]:
np.mean(matrix_A)

3.8

In [ ]:
np.mean(matrix_A[:,3])

4.0

In [ ]:
np.mean(matrix_A, axis=0)

array([3.5 , 4.5 , 2.75, 4.  , 4.25])

In [ ]:
np.mean(matrix_A, axis=1)

array([4.4, 4.2, 4.6, 2. ])

In [ ]:
matrix_A.mean()

3.8

In [ ]:
np.mean(matrix_A, axis=1, dtype= np.int64)

array([4, 4, 4, 2])

In [ ]:
np.min(matrix_A)

1

In [ ]:
np.min(matrix_A[2])

2

In [ ]:
np.amin(matrix_A)

1

In [ ]:
np.minimum(matrix_A[1], matrix_A[3])

array([2, 3, 1, 2, 2])

In [ ]:
np.minimum.reduce(matrix_A)

array([2, 3, 1, 2, 2])

In [ ]:
np.min(matrix_A, axis=0)

array([2, 3, 1, 2, 2])

In [ ]:
np.max(matrix_A)

9

In [ ]:
np.maximum.reduce(matrix_A)

array([5, 9, 4, 8, 6])

np.ptp()

Returns the difference between the highest and lowest values within an array

np.max() - np.min()

In [ ]:
matrix_A

array([[2, 3, 4, 8, 5],
       [5, 3, 3, 4, 6],
       [5, 9, 3, 2, 4],
       [2, 3, 1, 2, 2]])

In [ ]:
np.ptp(matrix_A)

8

In [ ]:
np.ptp(matrix_A, axis = 0)

array([3, 6, 3, 6, 4])

In [ ]:
np.ptp(matrix_A, axis = 1)

array([6, 3, 7, 2])

In [ ]:
np.sort(matrix_A, axis = None)

array([1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 8, 9])

In [ ]:
type(np.percentile(matrix_A, 70))

numpy.float64

In [ ]:
np.percentile(matrix_A, 100)

9.0

In [ ]:
np.quantile(matrix_A, 0.70, interpolation = "nearest")

<ipython-input-27-0616a358fb50>:1: DeprecationWarning: the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
  np.quantile(matrix_A, 0.70, interpolation = "nearest")


4

In [29]:
np.median(matrix_A)

3.0