<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Statistics_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.mean()

In [2]:
matrix_A = np.array([[2,3,4,8,5], [5,3,3,4,6], [5,9,3,2,4], [2,3,1,2,2]])
matrix_A

array([[2, 3, 4, 8, 5],
       [5, 3, 3, 4, 6],
       [5, 9, 3, 2, 4],
       [2, 3, 1, 2, 2]])

In [3]:
np.mean(matrix_A)

3.8

In [4]:
np.mean(matrix_A[:,3])

4.0

In [5]:
np.mean(matrix_A, axis=0)

array([3.5 , 4.5 , 2.75, 4.  , 4.25])

In [6]:
np.mean(matrix_A, axis=1)

array([4.4, 4.2, 4.6, 2. ])