<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Working_with_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Slicing

In [2]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

Basic Slicing

In [3]:
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
matrix_A[0:0]

array([], shape=(0, 3), dtype=int64)

In [5]:
matrix_A[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(matrix_A[:,:])

numpy.ndarray

In [7]:
matrix_A[2:]

array([], shape=(0, 3), dtype=int64)

In [8]:
matrix_A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix_A[1:]

array([[4, 5, 6]])

In [10]:
matrix_A[1]

array([4, 5, 6])

In [11]:
matrix_A[:-1]

array([[1, 2, 3]])

In [12]:
matrix_A[:,1:]

array([[2, 3],
       [5, 6]])

In [13]:
matrix_A[1:,1:]

array([[5, 6]])

Stepwise Slicing

In [14]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [15]:
matrix_B[:,:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [16]:
matrix_B[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

Conditional Slicing

In [17]:
matrix_C = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [18]:
matrix_C[:,0]

array([1, 3, 4])

In [19]:
matrix_C[:,0] > 2

array([False,  True,  True])

In [20]:
matrix_C[:,:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [21]:
matrix_C[matrix_C[:,:] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [22]:
matrix_C[matrix_C[:,:] >= 2]

array([2, 3, 6, 6, 7, 4, 4, 5, 3, 8])

In [23]:
matrix_C[matrix_C[:,:] % 2 == 0]

array([2, 0, 6, 6, 4, 4, 8, 0])