<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Working_with_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Slicing

In [3]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

Basic Slicing

In [4]:
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matrix_A[0:0]

array([], shape=(0, 3), dtype=int64)

In [6]:
matrix_A[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(matrix_A[:,:])

numpy.ndarray

In [8]:
matrix_A[2:]

array([], shape=(0, 3), dtype=int64)

In [10]:
matrix_A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
matrix_A[1:]

array([[4, 5, 6]])

In [12]:
matrix_A[1]

array([4, 5, 6])